### PR TITLE
Update c26492.md

### PR DESCRIPTION
**Pull request by JayFiDev**
Improved translation

### CODE REVIEW

**Comment by JayFiDev** [comment]
I am not sure, if translating those c26xxx files is worth it. Shall i continue with more?

**Comment by v-radelg** [comment]
Hello @JayFiDev  , thank for your contribution.

Please check it again because the date has a word added (04/26/2018Finden). Please fix the contribution so we can proceed. 

About the other files, please feel free to propose the suggestions you consider useful.

Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by JayFiDev** [comment]
I have a problem with my repository, can't make the changes. I will close this one and do another pull request from a new forked repository, because the old one is not found any more. 

Sorry, still new to this github editing, think i made an error.

**Comment by JayFiDev** [comment]
I just submitted another try! Thank you for the support! I think that was my problem!

**Comment by v-radelg** [comment]
We are glad to help

Kind regards, Microsoft C&E Localization Team

**Pull request closed without merging**
